---
apiVersion: v1
kind: Service
metadata:
  name: pdfjs
  namespace: sbos-apps
spec:
  type: ClusterIP
  selector:
    app: pdfjs
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdfjs
  namespace: sbos-apps
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: pdfjs
  template:
    metadata:
      labels:
        app: pdfjs
    spec:
      serviceAccountName: pdfjs-sa
      containers:
        - name: pdfjs
          image: docker.io/nginx:alpine
          ports:
            - containerPort: 8080
              name: http

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10


