// ============================================================
// bauth::domain::merge — merge_role_templates() (B45.D02)
//
// Recibe 12 role_code (uno por dominio D1-D12, None = sin configurar),
// consulta idn_role_d* en BD, conjuga secciones en JSONB completo
// de 14 secciones, y retorna el template listo para idn_role_template.
//
// Precedencia: D9>D8>D1>D3>D2>D10>D4>D6>D7>D5>D12>D11
// DOC-SBOS-001 N3 · BAUTH-ROLTEMPLATE-SECCIONES.md v6.0
// ============================================================

use serde_json::{json, Value};
use sqlx::PgPool;
use std::collections::BTreeMap;

/// Mapa dominio → nombre de sección en el template JSONB v6.0.
const SECTION_NAMES: [(&str, u8); 12] = [
    ("logical_access", 1),
    ("physical_access", 2),
    ("financial", 3),
    ("temporal", 4),
    ("biometric", 5),
    ("geospatial", 6),
    ("network", 7),
    ("context", 8),
    ("credentials", 9),
    ("delegation", 10),
    ("audit", 11),
    ("blockchain", 12),
];

/// Orden canónico de precedencia para resolución de conflictos.
/// Si dos dominios definen la misma clave, gana el de mayor precedencia.
const PRECEDENCE_ORDER: [u8; 12] = [9, 8, 1, 3, 2, 10, 4, 6, 7, 5, 12, 11];

/// Resultado del merge: template JSONB completo + metadata.
#[derive(Debug, Clone, serde::Serialize)]
pub struct MergeResult {
    /// Template JSONB con las 14 secciones del RolTemplate v6.0.
    pub template: Value,
    /// Dominios que contribuyeron efectivamente al merge.
    pub domains_merged: Vec<u8>,
    /// Dominios sin configuración (None en la entrada).
    pub domains_skipped: Vec<u8>,
}

/// Fila cargada desde idn_role_d{n}.
#[derive(Debug, sqlx::FromRow)]
struct RoleRow {
    role_name: Value,
    config: Value,
}

/// Mergea 12 plantillas de dominio en un solo RolTemplate JSONB.
///
/// # Argumentos
/// * `pg` — Pool de PostgreSQL.
/// * `role_codes` — Slice de 12 elementos (índice 0=D1, 11=D12). None = sin configurar.
/// * `role_id` — ID del rol resultante.
/// * `tier` — Tier del rol (SU, SYS, BIZ_N1...).
/// * `status` — Estado inicial (DEFINIDO por defecto).
///
/// # Precedencia
/// Si dos dominios contribuyen la misma clave JSON, gana el de mayor precedencia.
/// Orden: D9 > D8 > D1 > D3 > D2 > D10 > D4 > D6 > D7 > D5 > D12 > D11.
pub async fn merge_role_templates(
    pg: &PgPool,
    role_codes: &[Option<String>; 12],
    role_id: &str,
    tier: &str,
    status: &str,
) -> Result<MergeResult, String> {
    let mut template = json!({
        "role": {
            "id": role_id,
            "tier": tier,
            "status": status,
            "version": "6.0.0",
            "name": {"es": format!("Rol {}", role_id), "en": format!("Role {}", role_id)},
            "description": {"es": "Rol generado por merge_role_templates()", "en": "Role generated by merge_role_templates()"},
            "merge_source": "merge_role_templates()",
            "merged_at": chrono::Utc::now().to_rfc3339()
        }
    });

    let mut domains_merged: Vec<u8> = Vec::new();
    let mut domains_skipped: Vec<u8> = Vec::new();
    let mut sections_added: BTreeMap<String, u8> = BTreeMap::new(); // section_name → domain

    // ── Iterar en ORDEN DE PRECEDENCIA ──────────────────────
    for &domain in &PRECEDENCE_ORDER {
        let idx = (domain - 1) as usize;
        let section_name = SECTION_NAMES.iter()
            .find(|(_, d)| *d == domain)
            .map(|(n, _)| n)
            .unwrap_or(&"unknown");

        if let Some(ref code) = role_codes[idx] {
            // Cargar config desde BD
            match load_domain_config(pg, domain, code).await {
                Ok(role_row) => {
                    // Detectar si el config ya contiene la sección anidada
                    let section_data = if let Some(inner) = role_row.config.get(*section_name) {
                        inner.clone()
                    } else {
                        role_row.config.clone()
                    };

                    // Aplicar precedencia: si ya existe esta sección de un dominio
                    // con MENOR precedencia, se sobreescribe. Si el existente tiene
                    // MAYOR precedencia, se conserva.
                    let should_replace = match sections_added.get(*section_name) {
                        Some(&existing_domain) => {
                            let existing_prec = precedence_rank(existing_domain);
                            let new_prec = precedence_rank(domain);
                            new_prec < existing_prec // menor rank = mayor precedencia
                        }
                        None => true,
                    };

                    if should_replace {
                        template[*section_name] = section_data;
                        sections_added.insert(section_name.to_string(), domain);
                    }

                    // Actualizar nombre desde D1 si está presente
                    if domain == 1 {
                        template["role"]["name"] = role_row.role_name.clone();
                    }

                    domains_merged.push(domain);
                }
                Err(e) => {
                    tracing::warn!(domain, code, error = %e, "no se pudo cargar config de dominio");
                }
            }
        } else {
            domains_skipped.push(domain);
        }
    }

    Ok(MergeResult {
        template,
        domains_merged,
        domains_skipped,
    })
}

/// Carga el config de un dominio desde la tabla idn_role_d{n}.
async fn load_domain_config(
    pg: &PgPool,
    domain: u8,
    role_code: &str,
) -> Result<RoleRow, String> {
    let table = format!("bauth.idn_role_d{}", domain);
    let query = format!(
        "SELECT role_name, config FROM {} WHERE role_code = $1 AND is_active = true",
        table
    );

    sqlx::query_as::<_, RoleRow>(&query)
        .bind(role_code)
        .fetch_optional(pg)
        .await
        .map_err(|e| format!("error consultando {}: {}", table, e))?
        .ok_or_else(|| format!("role_code {} no encontrado en {}", role_code, table))
}

/// Retorna el rank de precedencia (menor = mayor precedencia).
fn precedence_rank(domain: u8) -> usize {
    PRECEDENCE_ORDER.iter().position(|&d| d == domain).unwrap_or(99)
}

/// Valida que un array de 12 role_codes no tenga conflictos de SoD
/// entre los dominios seleccionados. Retorna lista de conflictos encontrados.
pub fn validate_merge_no_conflicts(role_codes: &[Option<String>; 12]) -> Vec<String> {
    let mut warnings: Vec<String> = Vec::new();

    // Regla: si D3 (financiero) tiene CAJERO, D10 no puede tener DELEGACION_SUPERVISOR
    if let (Some(ref d3), Some(ref d10)) = (&role_codes[2], &role_codes[9]) {
        if d3.contains("CAJERO") && d10.contains("SUPERVISOR") {
            warnings.push(
                "Conflicto SoD: Cajero (D3) no puede tener Delegación Supervisor (D10)".into()
            );
        }
    }

    // Regla: si D1 es AUDITOR, D3 no puede ser APROBADOR
    if let (Some(ref d1), Some(ref d3)) = (&role_codes[0], &role_codes[2]) {
        if d1.contains("AUDITOR") && d3.contains("APROBADOR") {
            warnings.push(
                "Conflicto SoD: Auditor (D1) no puede ser Aprobador (D3)".into()
            );
        }
    }

    // Regla: D9 AAL1 no compatible con D3 aprobador > N1
    if let (Some(ref d9), Some(ref d3)) = (&role_codes[8], &role_codes[2]) {
        if d9.contains("AAL1") && d3.contains("APROBADOR") {
            warnings.push(
                "Conflicto LoA: AAL1 (D9) insuficiente para Aprobador financiero (D3)".into()
            );
        }
    }

    warnings
}

// ─── JSON-RPC Handler ──────────────────────────────────────

use crate::server::jsonrpc::{JsonRpcError, JsonRpcHandler};

pub struct MergeRoleTemplatesHandler {
    pub pg_pool: Option<PgPool>,
}

#[async_trait::async_trait]
impl JsonRpcHandler for MergeRoleTemplatesHandler {
    async fn handle(&self, params: Value) -> Result<Value, JsonRpcError> {
        let pg = self.pg_pool.as_ref().ok_or_else(|| JsonRpcError {
            code: -32000,
            message: "base de datos no disponible para merge".into(),
            data: None,
        })?;

        // Extraer role_codes del array de params
        let mut role_codes: [Option<String>; 12] = Default::default();
        if let Some(arr) = params.get("role_codes").and_then(|v| v.as_array()) {
            for (i, item) in arr.iter().enumerate() {
                if i >= 12 { break; }
                role_codes[i] = item.as_str().map(|s| s.to_string());
            }
        }

        let role_id = params.get("role_id").and_then(|v| v.as_str()).unwrap_or("ROL-MERGED");
        let tier = params.get("tier").and_then(|v| v.as_str()).unwrap_or("BIZ_N3");
        let status = params.get("status").and_then(|v| v.as_str()).unwrap_or("DEFINIDO");

        // Validar conflictos SoD
        let sod_warnings = validate_merge_no_conflicts(&role_codes);

        // Ejecutar merge
        let result = merge_role_templates(pg, &role_codes, role_id, tier, status)
            .await
            .map_err(|e| JsonRpcError {
                code: -32000,
                message: format!("error en merge: {}", e),
                data: None,
            })?;

        Ok(json!({
            "role_id": role_id,
            "tier": tier,
            "status": status,
            "domains_merged": result.domains_merged,
            "domains_merged_count": result.domains_merged.len(),
            "domains_skipped": result.domains_skipped,
            "sod_warnings": sod_warnings,
            "template": result.template,
        }))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_precedence_order() {
        // D9 debe ser primero (mayor precedencia)
        assert_eq!(PRECEDENCE_ORDER[0], 9);
        // D11 debe ser último (menor precedencia)
        assert_eq!(PRECEDENCE_ORDER[11], 11);
    }

    #[test]
    fn test_validate_no_conflicts_clean() {
        let codes: [Option<String>; 12] = Default::default();
        let warnings = validate_merge_no_conflicts(&codes);
        assert!(warnings.is_empty());
    }

    #[test]
    fn test_validate_conflict_cajero_supervisor() {
        let mut codes: [Option<String>; 12] = Default::default();
        codes[2] = Some("D3-CAJERO".into());
        codes[9] = Some("D10-DELEGACION-SUPERVISOR".into());
        let warnings = validate_merge_no_conflicts(&codes);
        assert!(!warnings.is_empty());
    }

    #[test]
    fn test_validate_conflict_auditor_aprobador() {
        let mut codes: [Option<String>; 12] = Default::default();
        codes[0] = Some("D1-AUDITOR".into());
        codes[2] = Some("D3-APROBADOR-N1".into());
        let warnings = validate_merge_no_conflicts(&codes);
        assert!(!warnings.is_empty());
    }

    #[test]
    fn test_precedence_rank_d9_vs_d11() {
        assert!(precedence_rank(9) < precedence_rank(11));
    }

    #[test]
    fn test_all_domains_have_section_names() {
        for d in 1..=12u8 {
            let found = SECTION_NAMES.iter().any(|(_, dd)| *dd == d);
            assert!(found, "Dominio {} sin nombre de sección", d);
        }
    }
}
