---
apiVersion: v1
kind: Service
metadata:
  name: directus
  namespace: sbos-apps
spec:
  type: ClusterIP
  selector:
    app: directus
  ports:
    - name: http
      port: 8055
      targetPort: 8055
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: directus
  namespace: sbos-apps
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: directus
  template:
    metadata:
      labels:
        app: directus
    spec:
      serviceAccountName: directus-sa
      containers:
        - name: directus
          image: docker.io/directus/directus:11.3
          ports:
            - containerPort: 8055
              name: http

          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8055
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8055
            initialDelaySeconds: 10
            periodSeconds: 10


