---
apiVersion: v1
kind: Service
metadata:
  name: k6
  namespace: sbos-ops
spec:
  type: ClusterIP
  selector:
    app: k6
  ports:
    - name: http
      port: 6565
      targetPort: 6565
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6
  namespace: sbos-ops
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: k6
  template:
    metadata:
      labels:
        app: k6
    spec:
      serviceAccountName: k6-sa
      containers:
        - name: k6
          image: docker.io/grafana/k6:0.52
          ports:
            - containerPort: 6565
              name: http

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 6565
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 6565
            initialDelaySeconds: 10
            periodSeconds: 10


