---
apiVersion: v1
kind: Service
metadata:
  name: citus
  namespace: sbos-data
spec:
  type: ClusterIP
  selector:
    app: citus
  ports:
    - name: http
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: citus
  namespace: sbos-data
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: citus
  template:
    metadata:
      labels:
        app: citus
    spec:
      serviceAccountName: citus-sa
      containers:
        - name: citus
          image: docker.io/citusdata/citus:12.1
          ports:
            - containerPort: 5432
              name: http

          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 10


