---
apiVersion: v1
kind: Service
metadata:
  name: mattermost
  namespace: sbos-comms
spec:
  type: ClusterIP
  selector:
    app: mattermost
  ports:
    - name: http
      port: 8065
      targetPort: 8065
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost
  namespace: sbos-comms
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mattermost
  template:
    metadata:
      labels:
        app: mattermost
    spec:
      serviceAccountName: mattermost-sa
      containers:
        - name: mattermost
          image: docker.io/mattermost/mattermost-enterprise-edition:9.11
          ports:
            - containerPort: 8065
              name: http

          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 8065
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8065
            initialDelaySeconds: 10
            periodSeconds: 10


