---
apiVersion: v1
kind: Service
metadata:
  name: kimios
  namespace: sbos-docs
spec:
  type: ClusterIP
  selector:
    app: kimios
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimios
  namespace: sbos-docs
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: kimios
  template:
    metadata:
      labels:
        app: kimios
    spec:
      serviceAccountName: kimios-sa
      containers:
        - name: kimios
          image: docker.io/kimios/kimios:1.3
          ports:
            - containerPort: 8080
              name: http

          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10


