---
apiVersion: v1
kind: Service
metadata:
  name: roundcube
  namespace: sbos-comms
spec:
  type: ClusterIP
  selector:
    app: roundcube
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundcube
  namespace: sbos-comms
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: roundcube
  template:
    metadata:
      labels:
        app: roundcube
    spec:
      serviceAccountName: roundcube-sa
      containers:
        - name: roundcube
          image: docker.io/roundcube/roundcubemail:1.6
          ports:
            - containerPort: 80
              name: http

          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10


