---
apiVersion: v1
kind: Service
metadata:
  name: clamav
  namespace: sbos-comms
spec:
  type: ClusterIP
  selector:
    app: clamav
  ports:
    - name: http
      port: 3310
      targetPort: 3310
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
  namespace: sbos-comms
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: clamav
  template:
    metadata:
      labels:
        app: clamav
    spec:
      serviceAccountName: clamav-sa
      containers:
        - name: clamav
          image: docker.io/clamav/clamav:1.3
          ports:
            - containerPort: 3310
              name: http

          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3310
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3310
            initialDelaySeconds: 10
            periodSeconds: 10


