-- bauth_T161b__idn_policy_node_type.sql — Seed generado de VPS SBOSDB
-- Filas: 12 · Idempotente: ON CONFLICT DO NOTHING
SET lock_timeout = '5s';

INSERT INTO bauth.idn_policy_node_type VALUES ('tenant', 'TNT', 'Tenant', 'Tenant', 'Nodo raíz del árbol de políticas de un tenant. Cada tenant tiene su propio árbol independiente.', 'Root node of a tenant policy tree. Each tenant has its own independent tree.', true, 10, 'primary', 'muted', 700, 'md', false, 0.40, true, true) ON CONFLICT DO NOTHING;
INSERT INTO bauth.idn_policy_node_type VALUES ('domain', 'DOM', 'Dominio', 'Domain', 'Cabecera de un dominio de control. Agrupa bloques y políticas de un área funcional. Corresponde a los dominios D0–D99.', 'Control domain header. Groups blocks and policies for a functional area. Maps to domains D0–D99.', true, 20, 'primary', 'muted', 700, 'md', false, 0.40, false, true) ON CONFLICT DO NOTHING;
INSERT INTO bauth.idn_policy_node_type VALUES ('block', 'BLQ', 'Bloque', 'Block', 'Agrupación intermedia de objetos y políticas dentro de un dominio. Organiza secciones lógicas sin semántica de control propia.', 'Intermediate grouping of objects and policies within a domain. Organizes logical sections without own control semantics.', true, 30, 'foreground', 'muted', 700, 'base', false, 0.00, false, false) ON CONFLICT DO NOTHING;
INSERT INTO bauth.idn_policy_node_type VALUES ('object', 'OBJ', 'Objeto', 'Object', 'Estructura de datos JSONB. Representa una entidad de negocio o configuración. No contiene lógica de control.', 'JSONB data structure. Represents a business entity or configuration. Contains no control logic.', true, 40, 'muted', 'muted', 600, 'base', false, 0.00, true, false) ON CONFLICT DO NOTHING;
INSERT INTO bauth.idn_policy_node_type VALUES ('list', 'LST', 'Lista', 'List', 'Colección ordenada de ítems homogéneos. Usada para arrays de valores de configuración o permisos.', 'Ordered collection of homogeneous items. Used for arrays of configuration values or permissions.', true, 50, 'muted', 'muted', 600, 'base', false, 0.00, true, false) ON CONFLICT DO NOTHING;
INSERT INTO bauth.idn_policy_node_type VALUES ('policy_set', 'SET', 'Conjunto de Políticas', 'Policy Set', 'Agrupación lógica de políticas evaluadas como un conjunto bajo un algoritmo de combinación (permit-overrides, deny-overrides, etc.).', 'Logical grouping of policies evaluated as a set under a combining algorithm (permit-overrides, deny-overrides, etc.).', true, 60, 'primary', 'muted', 600, 'base', false, 0.00, true, false) ON CONFLICT DO NOTHING;
INSERT INTO bauth.idn_policy_node_type VALUES ('policy', 'POL', 'Política', 'Policy', 'Conjunción de condiciones que gobiernan el acceso a un resource. Contiene reglas y define el algoritmo de combinación.', 'Conjunction of conditions that govern access to a resource. Contains rules and defines the combining algorithm.', true, 70, 'primary', 'muted', 600, 'base', false, 0.00, true, false) ON CONFLICT DO NOTHING;
INSERT INTO bauth.idn_policy_node_type VALUES ('rule', 'RGL', 'Regla', 'Rule', 'Una o más evaluaciones atómicas encadenadas con su efecto (Permit/Deny). Patrón: eval [op_lógico eval]* efecto.', 'One or more atomic evaluations chained with their effect (Permit/Deny). Pattern: eval [logical_op eval]* effect.', true, 80, 'amber', 'muted', 600, 'base', false, 0.00, true, false) ON CONFLICT DO NOTHING;
INSERT INTO bauth.idn_policy_node_type VALUES ('atom', 'ATM', 'Átomo', 'Atom', 'Evaluación atómica: propiedad / operador / valor / efecto. Unidad mínima de decisión del PDP. Ocupa una posición de bit en el BitMask.', 'Atomic evaluation: property / operator / value / effect. Minimum decision unit of the PDP. Occupies one bit position in the BitMask.', true, 90, 'teal', 'teal', 600, 'sm', false, 0.00, true, false) ON CONFLICT DO NOTHING;
INSERT INTO bauth.idn_policy_node_type VALUES ('attribute', 'ATR', 'Atributo', 'Attribute', 'Hoja de datos: clave → valor libre. Almacena metadatos, parámetros de configuración o claims del contexto.', 'Data leaf: key → free value. Stores metadata, configuration parameters or context claims.', true, 100, 'muted', 'muted', 500, 'sm', true, 0.00, false, false) ON CONFLICT DO NOTHING;
INSERT INTO bauth.idn_policy_node_type VALUES ('enum', 'ENM', 'Enumerado', 'Enum', 'Hoja de datos: clave → valor de conjunto fijo. El editor presenta un menú contextual con las opciones disponibles.', 'Data leaf: key → value from a fixed set. The editor presents a context menu with available options.', true, 110, 'violet', 'violet', 600, 'sm', true, 0.00, true, false) ON CONFLICT DO NOTHING;
INSERT INTO bauth.idn_policy_node_type VALUES ('event', 'EVT', 'Evento', 'Event', 'Disparador de políticas basado en eventos del sistema o del usuario. Activa evaluaciones reactivas en el motor CAEP.', 'Policy trigger based on system or user events. Activates reactive evaluations in the CAEP engine.', true, 120, 'amber', 'muted', 600, 'base', false, 0.00, true, false) ON CONFLICT DO NOTHING;

SELECT 'T161b__idn_policy_node_type: ' || 12 || ' filas' AS resultado;
