-- =============================================================================
-- bauth_T999__cfg_policy_library.sql — Seed: Biblioteca de Políticas + Traducciones
-- Tablas: cfg_key_translation · framework_raw · cfg_policy_library (CTE)
-- Idempotencia: TRUNCATE + recarga (catálogos de referencia)
-- =============================================================================
SET lock_timeout = '5s';

-- ══════════════════════════════════════════════════════════════════════
-- FASE 1: cfg_key_translation — 221 claves inglés→español
-- ══════════════════════════════════════════════════════════════════════
TRUNCATE TABLE bauth.cfg_key_translation RESTART IDENTITY CASCADE;
INSERT INTO bauth.cfg_key_translation (key_en, key_es) VALUES
('enabled','habilitado'),('disabled','deshabilitado'),('required','requerido'),('optional','opcional'),
('active','activo'),('inactive','inactivo'),('description','descripcion'),('status','estado'),
('level','nivel'),('type','tipo'),('mode','modo'),('key','clave'),('name','nombre'),('value','valor'),
('source','fuente'),('target','destino'),('security','seguridad'),('policies','politicas'),
('rules','reglas'),('actions','acciones'),('events','eventos'),('alerts','alertas'),
('frequency','frecuencia'),('period','periodo'),('duration','duracion'),('interval','intervalo'),
('timeout','tiempoEspera'),('threshold','umbral'),('limit','limite'),('weight','peso'),
('priority','prioridad'),('access','acceso'),('control','control'),('authentication','autenticacion'),
('authorization','autorizacion'),('identity','identidad'),('session','sesion'),('token','token'),
('password','contrasena'),('credential','credencial'),('certificate','certificado'),
('encryption','cifrado'),('signature','firma'),('algorithm','algoritmo'),('protocol','protocolo'),
('standard','estandar'),('compliance','cumplimiento'),('audit','auditoria'),('log','registro'),
('monitoring','monitoreo'),('review','revision'),('approval','aprobacion'),('risk','riesgo'),
('threat','amenaza'),('trust','confianza'),('privacy','privacidad'),('integrity','integridad'),
('confidentiality','confidencialidad'),('availability','disponibilidad'),('resilience','resiliencia'),
('recovery','recuperacion'),('backup','respaldo'),('rotation','rotacion'),('expiration','expiracion'),
('revocation','revocacion'),('provisioning','aprovisionamiento'),('delegation','delegacion'),
('segregation','segregacion'),('separation','separacion'),('minimum','minimo'),('maximum','maximo'),
('default','porDefecto'),('custom','personalizado'),('internal','interno'),('external','externo'),
('public','publico'),('private','privado'),('role','rol'),('user','usuario'),('group','grupo'),
('permission','permiso'),('profile','perfil'),('account','cuenta'),('device','dispositivo'),
('network','red'),('data','datos'),('api','api'),('service','servicio'),('application','aplicacion'),
('workload','cargaTrabajo'),('container','contenedor'),('cluster','cluster'),
('namespace','espacioNombres'),('resource','recurso'),('policy','politica'),
('configuration','configuracion'),('management','gestion'),('protection','proteccion'),
('detection','deteccion'),('prevention','prevencion'),('response','respuesta'),
('validation','validacion'),('verification','verificacion'),('testing','prueba'),
('assessment','evaluacion'),('classification','clasificacion'),('retention','retencion'),
('masking','enmascaramiento'),('anonymization','anonimizacion'),('tokenization','tokenizacion'),
('passwordPolicy','politicaContrasena'),('mfaRequirements','requisitosMFA'),
('phishingResistant','resistentePhishing'),('blocklistScreening','filtroBlocklist'),
('geoFencing','geoCerca'),('regionAware','conscienteRegion'),
('dataSovereignty','soberaniaDatos'),('breakGlass','romperCristal'),
('justInTime','justoATiempo'),('segregationOfDuties','segregacionFunciones'),
('approvalChain','cadenaAprobacion'),('temporaryAccess','accesoTemporal'),
('emergencyOverride','anulacionEmergencia'),('bestPractices','mejoresPracticas'),
('requirements','requisitos'),('features','caracteristicas'),
('implementation','implementacion'),('orchestration','orquestacion'),
('automation','automatizacion'),('synchronization','sincronizacion'),
('replication','replicacion'),('federation','federacion'),('escalation','escalacion'),
('integration','integracion'),('habilitado','habilitado'),('requerido','requerido'),
('intervalo','intervalo'),('estrategia','estrategia'),('rotacionClaves','rotacionClaves'),
('gestionTokens','gestionTokens'),('seguridad','seguridad'),
('intervaloAdaptativo','intervaloAdaptativo'),('factoresRiesgo','factoresRiesgo'),
('intervaloMaximo','intervaloMaximo'),('intervaloMinimo','intervaloMinimo'),
('frecuencia','frecuencia'),('tipo','tipo'),('peso','peso'),
('anonimizacion','anonimizacion'),('revocacion','revocacion'),
('renovacion','renovacion'),('cicloVida','cicloVida'),
('certificados','certificados'),('firmaDigital','firmaDigital'),
('sessionManager','gestorSesiones'),('sessionTimeout','tiempoEsperaSesion'),
('concurrentSessions','sesionesConcurrentes'),('loggingSystem','sistemaRegistro'),
('auditTrail','pistaAuditoria'),('eventLogging','registroEventos'),
('logRetention','retencionRegistros'),('incidentManagement','gestionIncidentes'),
('incidentResponse','respuestaIncidentes'),('detectionEngine','motorDeteccion'),
('escalationPolicies','politicasEscalacion'),('dataSecuritySystem','sistemaSeguridadDatos'),
('dataSecurityControls','controlesSeguridadDatos'),('dataClassification','clasificacionDatos'),
('accessControl','controlAcceso'),('accessPolicies','politicasAcceso'),
('policyEngine','motorPoliticas'),('continuousMonitoring','monitoreoContinuo'),
('highAvailability','altaDisponibilidad'),('disasterRecovery','recuperacionDesastres'),
('businessContinuity','continuidadNegocio'),('containerSecurity','seguridadContenedores'),
('runtimeProtection','proteccionEjecucion'),('admissionControl','controlAdmision'),
('podSecurity','seguridadPod'),('identityFederation','federacionIdentidad'),
('federationTrust','confianzaFederacion'),('apiSecurity','seguridadAPI'),
('endpointProtection','proteccionEndpoints'),('rateLimiting','limitacionTasa'),
('circuitBreaker','cortacircuitos'),('faultTolerance','toleranciaFallos'),
('cryptographicManagement','gestionCriptografica'),('keyManagement','gestionClaves'),
('secretsVault','bovedaSecretos'),('zeroTrustSystem','sistemaConfianzaCero'),
('zeroTrustInfrastructure','infraestructuraConfianzaCero'),
('blockchainSecurity','seguridadBlockchain'),('aiSecurity','seguridadIA'),
('modelProtection','proteccionModelos'),('microservicesSystem','sistemaMicroservicios'),
('serviceMesh','mallaServicios'),('deviceManagement','gestionDispositivos'),
('postQuantumSystem','sistemaPostCuantico'),('hybridMode','modoHibrido'),
('keyExchange','intercambioClaves'),('digitalSignatures','firmasDigitales'),
('sanctumEnhanced','sanctumMejorado'),('tokenManagement','gestionTokens'),
('keyRotation','rotacionClaves'),('adaptiveInterval','intervaloAdaptativo'),
('maxInterval','intervaloMaximo'),('minInterval','intervaloMinimo'),('riskFactors','factoresRiesgo'),
('threatLevel','nivelAmenaza'),('accessPatterns','patronesAcceso'),
('securityIncidents','incidentesSeguridad'),('strategy','estrategia'),('proactive','proactivo'),
('riskEngine','motorRiesgo'),('riskScore','puntuacionRiesgo'),('contextEngine','motorContexto'),
('deviceAnalysis','analisisDispositivo'),('locationAnalysis','analisisUbicacion'),
('networkAnalysis','analisisRed'),('behavioralAnalysis','analisisConductual'),
('threatDetection','deteccionAmenazas'),('anomalyDetection','deteccionAnomalias');

SELECT 'cfg_key_translation: ' || count(*) || ' claves' FROM bauth.cfg_key_translation;
