-- bauth_T385__auth_saga_catalog.sql — Seed generado de VPS SBOSDB
-- Filas: 12 · Idempotente: ON CONFLICT DO NOTHING
SET lock_timeout = '5s';

INSERT INTO bauth.auth_saga_catalog VALUES ('019fb478-6503-769d-beae-7ee6af7da3b3', 'PASSWORD_MFA', '{"es": "Contraseña + MFA"}', '{"es": "Flujo estándar: contraseña + segundo factor TOTP/HOTP/WebAuthn"}', '["PASSWORD", "MFA_CHALLENGE", "VERIFY_MFA"]', 'AAL1', 'AAL2', 300, false, true, 'ACTIVE', 10) ON CONFLICT DO NOTHING;
INSERT INTO bauth.auth_saga_catalog VALUES ('019fb478-6505-7efc-b6e3-a03cad17f9d2', 'PASSWORDLESS_FIDO2', '{"es": "Sin contraseña FIDO2"}', '{"es": "Autenticación passkey nativa — sin contraseña, resistente a phishing"}', '["FIDO2_CHALLENGE", "VERIFY_ASSERTION"]', 'AAL1', 'AAL3', 120, false, false, 'ACTIVE', 20) ON CONFLICT DO NOTHING;
INSERT INTO bauth.auth_saga_catalog VALUES ('019fb478-6506-715d-8b3b-e090716f75a7', 'SOCIAL_BROKER', '{"es": "Bróker Social/OIDC"}', '{"es": "Redirección a IdP externo (Google/GitHub/Entra) con mapeo de claims"}', '["REDIRECT_TO_IDP", "RECEIVE_CALLBACK", "MAP_CLAIMS", "LOCAL_ACCOUNT_LINK"]', 'AAL1', 'AAL2', 600, false, false, 'ACTIVE', 30) ON CONFLICT DO NOTHING;
INSERT INTO bauth.auth_saga_catalog VALUES ('019fb478-6506-7213-b83f-0bf14749b436', 'SAML_SSO', '{"es": "SSO SAML 2.0"}', '{"es": "Single Sign-On vía SAML 2.0 SP-initiated o IdP-initiated"}', '["SP_INIT_AUTHNREQ", "IDP_PROCESS", "VALIDATE_ASSERTION", "ESTABLISH_SESSION"]', 'AAL1', 'AAL2', 600, false, false, 'ACTIVE', 40) ON CONFLICT DO NOTHING;
INSERT INTO bauth.auth_saga_catalog VALUES ('019fb478-6506-7279-86ae-a5796745cba4', 'DEVICE_AUTH', '{"es": "Device Authorization Flow"}', '{"es": "OAuth 2.0 Device Flow para dispositivos sin navegador (RFC 8628)"}', '["DEVICE_CODE_REQUEST", "USER_CODE_DISPLAY", "USER_AUTHORIZE", "POLL_TOKEN"]', 'AAL1', 'AAL1', 900, false, false, 'ACTIVE', 50) ON CONFLICT DO NOTHING;
INSERT INTO bauth.auth_saga_catalog VALUES ('019fb478-6506-72d4-922d-38f54d7843ee', 'STEP_UP_AAL2_AAL3', '{"es": "Step-Up AAL2→AAL3"}', '{"es": "Elevación temporal de LoA (RFC 9470) para operaciones sensibles"}', '["CURRENT_SESSION_VERIFY", "CHALLENGE_AAL3", "VERIFY_AAL3", "GRANT_STEP_UP"]', 'AAL2', 'AAL3', 180, false, true, 'ACTIVE', 60) ON CONFLICT DO NOTHING;
INSERT INTO bauth.auth_saga_catalog VALUES ('019fb478-6506-732a-96cb-c5cc55f48384', 'BREAKGLASS_EMERGENCY', '{"es": "Break-Glass Emergencia"}', '{"es": "Acceso de emergencia con trazabilidad total y alerta SIEM inmediata"}', '["EMERGENCY_TRIGGER", "DUAL_APPROVAL", "GRANT_ACCESS", "ALERT_SIEM"]', 'AAL2', 'AAL3', 3600, true, true, 'ACTIVE', 70) ON CONFLICT DO NOTHING;
INSERT INTO bauth.auth_saga_catalog VALUES ('019fb478-6506-7380-9bd4-9219917226e2', 'RECOVERY_FLOW', '{"es": "Recuperación de Cuenta"}', '{"es": "Flujo de recuperación: verificación de identidad + reset de credencial"}', '["IDENTITY_VERIFY", "RECOVERY_METHOD", "RESET_CREDENTIAL", "NOTIFY_USER"]', 'AAL1', 'AAL2', 1800, false, false, 'ACTIVE', 80) ON CONFLICT DO NOTHING;
INSERT INTO bauth.auth_saga_catalog VALUES ('019fb478-6506-7449-a77f-4254a2729cbf', 'CIBA_PUSH', '{"es": "CIBA Push MFA"}', '{"es": "Client-Initiated Backchannel Auth — push a bNotify para aprobar"}', '["CIBA_REQUEST", "PUSH_TO_DEVICE", "USER_APPROVE", "DELIVER_TOKEN"]', 'AAL1', 'AAL2', 120, false, true, 'ACTIVE', 90) ON CONFLICT DO NOTHING;
INSERT INTO bauth.auth_saga_catalog VALUES ('019fb478-6506-757a-9daa-955fc7bf12cf', 'TOKEN_EXCHANGE', '{"es": "Token Exchange"}', '{"es": "Intercambio de tokens entre servicios (RFC 8693) — impersonación controlada"}', '["VALIDATE_SUBJECT_TOKEN", "CHECK_PERMISSIONS", "ISSUE_ACTOR_TOKEN"]', 'AAL1', 'AAL2', 60, false, false, 'ACTIVE', 100) ON CONFLICT DO NOTHING;
INSERT INTO bauth.auth_saga_catalog VALUES ('019fb478-6506-75fc-8c39-cfedc68568fe', 'CLIENT_CREDENTIALS', '{"es": "Client Credentials M2M"}', '{"es": "Flujo máquina-a-máquina — sin usuario, solo client_id + secret/mTLS"}', '["VALIDATE_CLIENT", "CHECK_SCOPE", "ISSUE_ACCESS_TOKEN"]', 'AAL1', 'AAL1', 30, false, false, 'ACTIVE', 110) ON CONFLICT DO NOTHING;
INSERT INTO bauth.auth_saga_catalog VALUES ('019fb478-6506-7658-9928-d2bef4a0e1fa', 'M2M_MTLS', '{"es": "M2M mTLS Certificate"}', '{"es": "M2M con certificado cliente mTLS (RFC 8705) — máximo nivel M2M"}', '["VALIDATE_CERT", "CHECK_SCOPE", "ISSUE_BOUND_TOKEN"]', 'AAL1', 'AAL2', 30, false, false, 'ACTIVE', 120) ON CONFLICT DO NOTHING;

SELECT 'T385__auth_saga_catalog: ' || 12 || ' filas' AS resultado;
