---
apiVersion: v1
kind: Service
metadata:
  name: rocketchat
  namespace: sbos-comms
spec:
  type: ClusterIP
  selector:
    app: rocketchat
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat
  namespace: sbos-comms
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: rocketchat
  template:
    metadata:
      labels:
        app: rocketchat
    spec:
      serviceAccountName: rocketchat-sa
      containers:
        - name: rocketchat
          image: docker.io/rocketchat/rocket.chat:6.12
          ports:
            - containerPort: 3000
              name: http

          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10


