package packages

import (
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// FichaManifest holds the minimal fields for an auto-generated ficha manifest.
type FichaManifest struct {
	ID          string `yaml:"id"`
	Name        string `yaml:"name"`
	Version     string `yaml:"version"`
	Category    int    `yaml:"category"`
	Criticality bool   `yaml:"criticality"`
	Server      string `yaml:"server"`
	Description string `yaml:"description"`
	Backend     string `yaml:"backend"`
	InstalledAt string `yaml:"installed_at"`
}

// FichaGenerator creates ficha manifests for packages installed via the package manager.
type FichaGenerator struct {
	blibsDir string
}

// NewFichaGenerator creates a ficha generator rooted at the blibs directory.
func NewFichaGenerator(blibsDir string) *FichaGenerator {
	return &FichaGenerator{blibsDir: blibsDir}
}

// Generate creates a ficha directory and manifest for a newly installed package.
// Returns the ficha ID (sbos-app-<name>) and the manifest path.
func (g *FichaGenerator) Generate(name, version, backend string) (string, string, error) {
	fichaID := fmt.Sprintf("sbos-app-%s", sanitizeFichaName(name))
	fichaDir := filepath.Join(g.blibsDir, fichaID)

	if err := os.MkdirAll(fichaDir, 0755); err != nil {
		return "", "", fmt.Errorf("ficha: mkdir %s: %w", fichaDir, err)
	}

	manifest := fmt.Sprintf(`# manifest.yml — auto-generated by bosctl package manager
# Ficha for package: %s (backend: %s)
identity:
  id: "%s"
  name: "%s (auto)"
  version: "%s"
  category: 4
  criticality: false
  server: hostserver
  description: "Auto-generated ficha for package %s installed via %s"

workload:
  type: VirtualMachine
  namespace: sbos-installer
  replicas: 1

order:
  execution_order: 0
  timeout_minutes: 2

requirements:
  dependencies: []
  cpu_request: "10m"
  cpu_limit: "50m"
  memory_request: "16Mi"
  memory_limit: "32Mi"

deployment:
  strategy: Recreate

governance:
  auto_install: false

health:
  check_command: "%s_is_installed %s"
  check_interval_seconds: 86400
  check_timeout_seconds: 10
  consecutive_failures_threshold: 1

meta:
  backend: "%s"
  installed_at: "%s"
  managed_by: "bosctl-package-manager"
`, name, backend, fichaID, name, version, name, backend, backend, name, backend, time.Now().UTC().Format(time.RFC3339))

	manifestPath := filepath.Join(fichaDir, "manifest.yml")
	if err := os.WriteFile(manifestPath, []byte(manifest), 0644); err != nil {
		return "", "", fmt.Errorf("ficha: write manifest: %w", err)
	}

	taskCatalog := fmt.Sprintf(`#!/usr/bin/env bash
# task_catalog.sh — %s (auto-generated)
# Backend: %s — Package: %s
set -euo pipefail
FICHA="%s"

echo "__SBOS__STEP_START__ check-installed"
    if %s_is_installed %s; then
        echo "  %s: installed OK"
    else
        echo "  %s: NOT INSTALLED"
        exit 1
    fi
echo "__SBOS__STEP_OK__ check-installed"
`, fichaID, backend, name, fichaID, backend, name, name, name)

	taskPath := filepath.Join(fichaDir, "task_catalog.sh")
	if err := os.WriteFile(taskPath, []byte(taskCatalog), 0644); err != nil {
		return "", "", fmt.Errorf("ficha: write task_catalog: %w", err)
	}

	return fichaID, manifestPath, nil
}

// RemoveFicha removes the auto-generated ficha directory.
func (g *FichaGenerator) RemoveFicha(fichaID string) error {
	fichaDir := filepath.Join(g.blibsDir, fichaID)
	if err := os.RemoveAll(fichaDir); err != nil {
		return fmt.Errorf("ficha: remove %s: %w", fichaDir, err)
	}
	return nil
}

func sanitizeFichaName(name string) string {
	sanitized := make([]byte, 0, len(name))
	for _, c := range []byte(name) {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '-' || c == '_' {
			sanitized = append(sanitized, c)
		} else {
			sanitized = append(sanitized, '-')
		}
	}
	return string(sanitized)
}
