---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin4
  namespace: sbos-data
spec:
  type: ClusterIP
  selector:
    app: pgadmin4
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
  namespace: sbos-data
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: pgadmin4
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      serviceAccountName: pgadmin4-sa
      containers:
        - name: pgadmin4
          image: docker.io/dpage/pgadmin4:8.10
          ports:
            - containerPort: 80
              name: http

          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10


