---
apiVersion: v1
kind: Service
metadata:
  name: orangehrm
  namespace: sbos-apps
spec:
  type: ClusterIP
  selector:
    app: orangehrm
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orangehrm
  namespace: sbos-apps
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: orangehrm
  template:
    metadata:
      labels:
        app: orangehrm
    spec:
      serviceAccountName: orangehrm-sa
      containers:
        - name: orangehrm
          image: docker.io/orangehrm/orangehrm:6.0
          ports:
            - containerPort: 8080
              name: http

          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10


