---
apiVersion: v1
kind: Service
metadata:
  name: openvas
  namespace: sbos-identity
spec:
  type: ClusterIP
  selector:
    app: openvas
  ports:
    - name: http
      port: 9392
      targetPort: 9392
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvas
  namespace: sbos-identity
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: openvas
  template:
    metadata:
      labels:
        app: openvas
    spec:
      serviceAccountName: openvas-sa
      containers:
        - name: openvas
          image: docker.io/greenbone/gvmd:23.0
          ports:
            - containerPort: 9392
              name: http

          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 9392
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 9392
            initialDelaySeconds: 10
            periodSeconds: 10


