---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliance-check-sa
  namespace: sbos-installer
---
apiVersion: v1
kind: Service
metadata:
  name: compliance-check
  namespace: sbos-installer
spec:
  type: ClusterIP
  selector:
    app: compliance-check
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-check
  namespace: sbos-installer
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: compliance-check
  template:
    metadata:
      labels:
        app: compliance-check
    spec:
      serviceAccountName: compliance-check-sa
      containers:
        - name: compliance-check
          image: docker.io/aquasec/kube-bench:latest
          command: ["sleep", "infinity"]
          ports:
            - containerPort: 80
              name: http

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi