---
apiVersion: v1
kind: Service
metadata:
  name: airflow
  namespace: sbos-apps
spec:
  type: ClusterIP
  selector:
    app: airflow
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: sbos-apps
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      serviceAccountName: airflow-sa
      containers:
        - name: airflow
          image: docker.io/apache/airflow:2.10
          ports:
            - containerPort: 8080
              name: http

          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10


