---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-web-sa
  namespace: sbos-installer
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web
  namespace: sbos-installer
spec:
  type: ClusterIP
  selector:
    app: nginx-web
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
  namespace: sbos-installer
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      serviceAccountName: nginx-web-sa
      containers:
        - name: nginx-web
          image: docker.io/library/nginx:1.26
          ports:
            - containerPort: 80
              name: http

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10