---
apiVersion: v1
kind: Service
metadata:
  name: zammad
  namespace: sbos-apps
spec:
  clusterIP: None
  selector:
    app: zammad
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zammad
  namespace: sbos-apps
spec:
  serviceName: zammad
  replicas: 1
  selector:
    matchLabels:
      app: zammad
  template:
    metadata:
      labels:
        app: zammad
    spec:
      serviceAccountName: zammad-sa
      containers:
        - name: zammad
          image: docker.io/zammad/zammad:6.4
          ports:
            - containerPort: 3000
              name: http

          volumeMounts:
            - name: data
              mountPath: /var/lib/zammad
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: sbos-fast
        resources:
          requests:
            storage: 30Gi
