---
apiVersion: v1
kind: Service
metadata:
  name: authelia
  namespace: sbos-apps
spec:
  type: ClusterIP
  selector:
    app: authelia
  ports:
    - name: http
      port: 9091
      targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: sbos-apps
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      serviceAccountName: authelia-sa
      containers:
        - name: authelia
          image: docker.io/authelia/authelia:4.38
          ports:
            - containerPort: 9091
              name: http

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 10
            periodSeconds: 10


