---
apiVersion: v1
kind: Service
metadata:
  name: smartorc
  namespace: sbos-apps
spec:
  type: ClusterIP
  selector:
    app: smartorc
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartorc
  namespace: sbos-apps
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: smartorc
  template:
    metadata:
      labels:
        app: smartorc
    spec:
      serviceAccountName: smartorc-sa
      containers:
        - name: smartorc
          image: skull/smartorc:latest
          ports:
            - containerPort: 8080
              name: http

          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10


