---
apiVersion: v1
kind: Service
metadata:
  name: openmetadata
  namespace: sbos-apps
spec:
  type: ClusterIP
  selector:
    app: openmetadata
  ports:
    - name: http
      port: 8585
      targetPort: 8585
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmetadata
  namespace: sbos-apps
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: openmetadata
  template:
    metadata:
      labels:
        app: openmetadata
    spec:
      serviceAccountName: openmetadata-sa
      containers:
        - name: openmetadata
          image: docker.io/openmetadata/server:1.6
          ports:
            - containerPort: 8585
              name: http

          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 8585
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8585
            initialDelaySeconds: 10
            periodSeconds: 10


