---
apiVersion: v1
kind: Service
metadata:
  name: bareos
  namespace: sbos-ops
spec:
  clusterIP: None
  selector:
    app: bareos
  ports:
    - name: http
      port: 9101
      targetPort: 9101
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bareos
  namespace: sbos-ops
spec:
  serviceName: bareos
  replicas: 1
  selector:
    matchLabels:
      app: bareos
  template:
    metadata:
      labels:
        app: bareos
    spec:
      serviceAccountName: bareos-sa
      containers:
        - name: bareos
          image: docker.io/bareos/bareos-director:23.0
          ports:
            - containerPort: 9101
              name: http

          volumeMounts:
            - name: data
              mountPath: /var/lib/bareos
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 9101
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 9101
            initialDelaySeconds: 10
            periodSeconds: 10

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: sbos-fast
        resources:
          requests:
            storage: 500Gi
