---
apiVersion: v1
kind: Service
metadata:
  name: tabula
  namespace: sbos-docs
spec:
  type: ClusterIP
  selector:
    app: tabula
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tabula
  namespace: sbos-docs
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tabula
  template:
    metadata:
      labels:
        app: tabula
    spec:
      serviceAccountName: tabula-sa
      containers:
        - name: tabula
          image: docker.io/bitnami/tabula:1.0
          ports:
            - containerPort: 8080
              name: http

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10


