---
apiVersion: v1
kind: Service
metadata:
  name: tryton
  namespace: sbos-erp
spec:
  clusterIP: None
  selector:
    app: tryton
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tryton
  namespace: sbos-erp
spec:
  serviceName: tryton
  replicas: 2
  selector:
    matchLabels:
      app: tryton
  template:
    metadata:
      labels:
        app: tryton
    spec:
      serviceAccountName: tryton-sa
      containers:
        - name: tryton
          image: docker.io/tryton/tryton:7.4
          ports:
            - containerPort: 8000
              name: http

          volumeMounts:
            - name: data
              mountPath: /var/lib/tryton
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 50Gi
