---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: sbos-monitor
type: Opaque
stringData:
  db-password: "12345678abcD_admin"
  oidc-client-secret: "12345678abcD_admin"
  admin-password: "12345678abcD_admin"
