---
apiVersion: v1
kind: Service
metadata:
  name: symmetricds
  namespace: sbos-data
spec:
  type: ClusterIP
  selector:
    app: symmetricds
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symmetricds
  namespace: sbos-data
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: symmetricds
  template:
    metadata:
      labels:
        app: symmetricds
    spec:
      serviceAccountName: symmetricds-sa
      containers:
        - name: symmetricds
          image: docker.io/jumpmind/symmetricds:3.15
          ports:
            - containerPort: 8080
              name: http

          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10


