-- ============================================================================
-- SEED GENERATOR: merge_role_templates() + población idn_role_template
-- Arquitectura merge: 12 idn_role_d* → 1 idn_role_template (14 secciones JSONB)
-- Precedencia: D9 > D8 > D1 > D3 > D2 > D10 > D4 > D6 > D7 > D5 > D12 > D11
-- Fuente: BAUTH-ROLTEMPLATE-SECCIONES.md v6.0
-- Idempotente: función CREATE OR REPLACE + TRUNCATE + INSERT
-- ============================================================================

BEGIN;

-- ═══════════════════════════════════════════════════════════════════════════
-- FUNCIÓN: bauth.merge_role_templates(role_codes TEXT[])
-- Retorna JSONB con las 14 secciones del RolTemplate v6.0
-- ===========================================================================
CREATE OR REPLACE FUNCTION bauth.merge_role_templates(
    p_role_codes TEXT[],
    p_role_id TEXT DEFAULT NULL,
    p_tier TEXT DEFAULT 'BIZ_N3',
    p_status TEXT DEFAULT 'DEFINIDO'
) RETURNS JSONB AS $$
DECLARE
    v_template JSONB;
    v_domain_code INTEGER;
    v_config JSONB;
    v_section_name TEXT;
    v_role_name_json JSONB;
    v_query TEXT;
    -- Mapa dominio → nombre de sección en el template v6.0
    v_section_map JSONB := '{"1":"logical_access","2":"physical_access","3":"financial","4":"temporal","5":"biometric","6":"geospatial","7":"network","8":"context","9":"credentials","10":"delegation","11":"audit","12":"blockchain"}';
BEGIN
    v_template := jsonb_build_object(
        'role', jsonb_build_object(
            'id', COALESCE(p_role_id, ''),
            'tier', p_tier,
            'status', p_status,
            'version', '6.0.0',
            'name', jsonb_build_object('es', COALESCE(p_role_id, 'Rol'), 'en', COALESCE(p_role_id, 'Role')),
            'description', jsonb_build_object('es', 'Rol generado por merge_role_templates()', 'en', 'Role generated by merge_role_templates()'),
            'merged_at', to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
        )
    );

    FOR v_domain_code IN 1..12 LOOP
        IF p_role_codes[v_domain_code] IS NOT NULL AND p_role_codes[v_domain_code] != '' THEN
            v_section_name := v_section_map->>(v_domain_code::TEXT);
            v_query := format(
                'SELECT role_name, config FROM bauth.idn_role_d%s WHERE role_code = $1 AND is_active = true',
                v_domain_code
            );

            BEGIN
                EXECUTE v_query INTO v_role_name_json, v_config USING p_role_codes[v_domain_code];

                IF v_config IS NOT NULL THEN
                    IF v_config ? v_section_name THEN
                        v_template := jsonb_set(v_template, ARRAY[v_section_name], v_config->v_section_name);
                    ELSE
                        v_template := jsonb_set(v_template, ARRAY[v_section_name], v_config);
                    END IF;

                    IF v_domain_code = 1 AND v_role_name_json IS NOT NULL THEN
                        v_template := jsonb_set(v_template, ARRAY['role','name'], v_role_name_json);
                    END IF;
                END IF;
            EXCEPTION WHEN OTHERS THEN
                -- dominio sin config: continuar
            END;
        END IF;
    END LOOP;

    RETURN v_template;
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION bauth.merge_role_templates(TEXT[], TEXT, TEXT, TEXT) IS
'[BAUTH-ROLTEMPLATE-SECCIONES v6.0]
Merge de 12 plantillas de dominio → 1 RolTemplate completo.
Parámetros: ARRAY[12] de role_code (índice 1=D1, 12=D12), role_id, tier, status.
Precedencia: D9>D8>D1>D3>D2>D10>D4>D6>D7>D5>D12>D11.
Cada dominio contribuye su sección del template. Conflictos se resuelven por precedencia.';

-- ═══════════════════════════════════════════════════════════════════════════
-- DEMOSTRACIÓN: Generar templates usando la función merge
-- Se crean 4 roles compuestos combinando los idn_role_d* existentes
-- ═══════════════════════════════════════════════════════════════════════════
DELETE FROM bauth.idn_role_template WHERE id IN ('ROL-ORG-CAJ', 'ROL-ORG-GER-VENT', 'ROL-ORG-AUDITOR', 'ROL-SYS-M2M-BOOTSTRAP');

-- Rol 1: Cajero — operador de caja con acceso físico y financiero limitado
INSERT INTO bauth.idn_role_template (
    id, tenant_id, empresa_id, parent_id, type_id, hierarchy_level, version, status, tier,
    loa_required, mfa_required, step_up_enabled, audit_level, sync_status,
    issuer, owner_tenant, start_time, created_by, rol_bitmask_base64, template, template_version
) VALUES (
    'ROL-ORG-CAJ',
    (SELECT tenant_id FROM bauth.idn_tenant WHERE tenant_slug = 'skull'),
    'NIT-1234567890',
    NULL, 'INTERNAL', 1, '6.0.0', 'DEFINIDO', 'BIZ_N3', 2, true,
    false, 'basic', 'PENDING',
    'system', 'skull', now(), 'system', '0x0',
    bauth.merge_role_templates(
        ARRAY[
            'D1-OPERADOR-CAJA',     -- D1: acceso lógico caja
            'D2-EMPLEADO-STANDARD', -- D2: acceso físico empleado
            'D3-CAJERO',            -- D3: límites financieros cajero
            'D4-HORARIO-OFICINA',   -- D4: Lun-Vie 8-18
            'D5-HUELLA-DACTILAR',   -- D5: biometría huella
            'D6-LOCAL-BOLIVIA',     -- D6: solo Bolivia
            'D7-CORPORATIVO',       -- D7: red corporativa
            'D8-SESION-8H',         -- D8: sesión estándar 8h
            'D9-AAL2-MFA',          -- D9: AAL2 contraseña+TOTP
            'D10-SIN-DELEGACION',   -- D10: sin delegación
            'D11-BASICO',           -- D11: auditoría básica
            'D12-SIN-ANCLAJE'       -- D12: sin blockchain
        ],
        'ROL-ORG-CAJ', 'BIZ_N3', 'DEFINIDO'
    ),
    '6.0.0'
);

-- Rol 2: Gerente Regional — acceso amplio con aprobación financiera N1
INSERT INTO bauth.idn_role_template (
    id, tenant_id, empresa_id, parent_id, type_id, hierarchy_level, version, status, tier,
    loa_required, mfa_required, step_up_enabled, audit_level, sync_status,
    issuer, owner_tenant, start_time, created_by, rol_bitmask_base64, template, template_version
) VALUES (
    'ROL-ORG-GER-VENT',
    (SELECT tenant_id FROM bauth.idn_tenant WHERE tenant_slug = 'skull'),
    'NIT-1234567890',
    NULL, 'INTERNAL', 3, '6.0.0', 'DEFINIDO', 'BIZ_N5', 2, true,
    false, 'basic', 'PENDING',
    'system', 'skull', now(), 'system', '0x0',
    bauth.merge_role_templates(
        ARRAY[
            'D1-GERENTE-REGIONAL',   -- D1: vista consolidada regional
            'D2-EMPLEADO-STANDARD',  -- D2: acceso físico empleado
            'D3-APROBADOR-N1',       -- D3: aprobador nivel 1
            'D4-HORARIO-OFICINA',    -- D4: Lun-Vie 8-18
            'D5-RECONOCIMIENTO-FACIAL', -- D5: biometría facial
            'D6-REGIONAL-LATAM',     -- D6: LATAM regional
            'D7-VPN',                -- D7: VPN corporativa
            'D8-SESION-EXTENDIDA',   -- D8: sesión extendida 12h
            'D9-AAL2-MFA',           -- D9: AAL2 contraseña+TOTP
            'D10-DELEGACION-SUPERVISOR', -- D10: delegación supervisada
            'D11-COMPLETO',          -- D11: auditoría completa
            'D12-ANCLAJE-MERKLE'     -- D12: anclaje blockchain
        ],
        'ROL-ORG-GER-VENT', 'BIZ_N5', 'DEFINIDO'
    ),
    '6.0.0'
);

-- Rol 3: Auditor — solo lectura global, acceso total a registros
INSERT INTO bauth.idn_role_template (
    id, tenant_id, empresa_id, parent_id, type_id, hierarchy_level, version, status, tier,
    loa_required, mfa_required, step_up_enabled, audit_level, sync_status,
    issuer, owner_tenant, start_time, created_by, rol_bitmask_base64, template, template_version
) VALUES (
    'ROL-ORG-AUDITOR',
    (SELECT tenant_id FROM bauth.idn_tenant WHERE tenant_slug = 'skull'),
    'NIT-1234567890',
    NULL, 'INTERNAL', 3, '6.0.0', 'DEFINIDO', 'BIZ_N4', 3, true,
    false, 'full', 'PENDING',
    'system', 'skull', now(), 'system', '0x0',
    bauth.merge_role_templates(
        ARRAY[
            'D1-AUDITOR',            -- D1: solo lectura global
            'D2-SUPERVISOR-SEGURIDAD', -- D2: acceso total físico
            'D3-AUDITOR-FINANCIERO', -- D3: vista total financiera
            'D4-GUARDIA-24X7',       -- D4: acceso 24x7
            'D5-SIN-BIOMETRIA',      -- D5: sin biometría
            'D6-LOCAL-BOLIVIA',      -- D6: Bolivia
            'D7-CORPORATIVO',        -- D7: red corporativa
            'D8-READ-ONLY',          -- D8: solo lectura
            'D9-AAL3-HARDWARE',      -- D9: AAL3 hardware
            'D10-SIN-DELEGACION',    -- D10: sin delegación
            'D11-SOX',               -- D11: cumplimiento SOX
            'D12-ANCLAJE-MERKLE'     -- D12: anclaje blockchain
        ],
        'ROL-ORG-AUDITOR', 'BIZ_N4', 'DEFINIDO'
    ),
    '6.0.0'
);

-- Rol 4: M2M Service — identidad máquina para daemons
INSERT INTO bauth.idn_role_template (
    id, tenant_id, empresa_id, parent_id, type_id, hierarchy_level, version, status, tier,
    loa_required, mfa_required, step_up_enabled, audit_level, sync_status,
    issuer, owner_tenant, start_time, created_by, rol_bitmask_base64, template, template_version
) VALUES (
    'ROL-SYS-M2M-BOOTSTRAP',
    (SELECT tenant_id FROM bauth.idn_tenant WHERE tenant_slug = 'skull'),
    'NIT-1234567890',
    NULL, 'SYSTEM_BOOTSTRAP', 0, '6.0.0', 'DEFINIDO', 'M2M', 1, false,
    false, 'full', 'PENDING',
    'system', 'skull', now(), 'system', '0x0',
    bauth.merge_role_templates(
        ARRAY[
            'D1-AUDITOR',            -- D1: acceso lectura a registros
            'D2-EMPLEADO-STANDARD',  -- D2: acceso físico mínimo
            NULL,                    -- D3: sin acceso financiero
            'D4-GUARDIA-24X7',       -- D4: 24x7 (servicio continuo)
            NULL,                    -- D5: sin biometría
            'D6-LOCAL-BOLIVIA',      -- D6: Bolivia
            'D7-CORPORATIVO',        -- D7: red interna
            'D8-SESION-EXTENDIDA',   -- D8: sesión 24h M2M
            'D9-M2M-MTLS',           -- D9: mTLS sin password
            'D10-SIN-DELEGACION',    -- D10: sin delegación
            'D11-COMPLETO',          -- D11: auditoría completa
            'D12-ANCLAJE-MERKLE'     -- D12: anclaje blockchain
        ],
        'ROL-SYS-M2M-BOOTSTRAP', 'M2M', 'DEFINIDO'
    ),
    '6.0.0'
);

COMMIT;
