---
apiVersion: v1
kind: Service
metadata:
  name: solr
  namespace: sbos-docs
spec:
  clusterIP: None
  selector:
    app: solr
  ports:
    - name: http
      port: 8983
      targetPort: 8983
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr
  namespace: sbos-docs
spec:
  serviceName: solr
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      serviceAccountName: solr-sa
      containers:
        - name: solr
          image: docker.io/solr:9.5
          ports:
            - containerPort: 8983
              name: http

          volumeMounts:
            - name: data
              mountPath: /var/lib/solr
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 8983
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8983
            initialDelaySeconds: 10
            periodSeconds: 10

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: sbos-fast
        resources:
          requests:
            storage: 50Gi
